export const skillArr = [
  { name: "SKILLS", size: "100%", title: true },
  { name: "HTML5", size: "100%" },
  { name: "CSS3", size: "90%" },
  { name: "JavaScript", size: "80%" },
  { name: "React", size: "70%" },
  { name: "Node", size: "70%" },
  { name: "TypeScript", size: "70%" },
  { name: "PHP", size: "60%" },
  { name: "SQL", size: "60%" },
  { name: "MongoDD", size: "60%" },
  { name: "Vue", size: "50%" },
  { name: "Angular", size: "40%" },
  { name: "TOOLS", size: "100%", title: true },
  { name: "Mac", size: "100%" },
  { name: "Windows", size: "100%" },
  { name: "Github", size: "80%" },
  { name: "VScode", size: "80%" },
  { name: "LANGUAGES & METHODS", size: "100%", title: true },
  { name: "Swedish", size: "100%" },
  { name: "English", size: "90%" },
  { name: "Scrum", size: "80%" },
];
